---
roles:
  master:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 8192]
          - [modifyvm, !ruby/sym id, '--ioapic', 'on']
          - [modifyvm, !ruby/sym id, '--cpus', '2']
    provisioners:
      - type: shell
        name: "nameserver"
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
        sync_hosts: true

  windows_agent:
    communicator: winrm
    forwarded_ports:
          - { guest: 5985, host: 35985, auto_correct: true }
          - { guest: 3389, host: 33389, auto_correct: true }
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: hosts
        sync_hosts: true
      - type: shell
        name: "disable_uac"
        inline: 'Set-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA" -Value "0"'
      # The reload is important. It needs to happen for the name, domain, and
      # registry changes to take effect.
      - type: reload
      # Install the windows puppet agent using a PowerShell script. The
      # install_agent.ps1 script will set the agent certname it reads from
      # the system. The hosts provisioner should have configured these things
      # prior to the reboot.
      - type: shell
        name: "puppet_agent"
        path: "scripts/provisioners/puppet_agent_install.ps1"

  posix_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: shell
        name: "nameserver"
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
        sync_hosts: true
      - type: shell
        name: "puppet_agent"
        inline: "curl -sk https://master.inf.puppet.vm:8140/packages/current/install.bash | /bin/bash"
      - type: shell
        name: "puppet_complete"
        path: "scripts/provisioners/puppet_agent_complete.sh"

  darwin_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}

  posix_noagent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts, sync_hosts: true}
